# -*- coding: utf-8 -*-
"""Indian_Economics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uFrGkg7IcL7ia_ZirsCN8Wor4rjJUGFj
"""

import pandas as pd
import random

Data = pd.read_csv('year_gdp.csv')

Data.dropna()

Input = Data[['Year']]
Output = Data['Gdp']
Output

# new_data = Data[['Year', 'Gdp']]

# # Save the new data to a CSV file
# new_data.to_csv('year_gdp.csv', index=False)

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

X_train, X_test, y_train, y_test = train_test_split(Input, Output, test_size=0.2)

Poly_regressor = PolynomialFeatures(degree=4)
Poly_X = Poly_regressor.fit_transform(X_train)

joblib.dump(Poly_regressor, 'Poly_regressor.joblib')

Model = LinearRegression()
Model.fit(Poly_X, y_train)

import joblib
joblib.dump(Model, 'Model.joblib')

from sklearn.metrics import r2_score,mean_squared_error

Prediction = Model.predict(Poly_regressor.fit_transform(X_test))
print(Prediction)
Accuracy = r2_score(y_test, Prediction)
m = mean_squared_error
print(Accuracy)

data = pd.DataFrame([[2024]])
# print(Poly_regressor.fit_transform(data))
Predict = Model.predict(Poly_regressor.fit_transform(data))
print(Predict[0] /1000000000000)

import joblib
Poly_regressor = joblib.load('Poly_regressor.joblib')
Model = joblib.load('Model.joblib')

Data = Model.predict(Poly_regressor.fit_transform([[2050]]))
print(Data[0] / 1000000000000)